### PR TITLE
Update L25 ~ L28

### PR DESCRIPTION
**Pull request by hattiepwvi**
L25: immutable, self, empty(bool)==False, pulic, expression
L26: from implements, 0x150b7a02, immutable, self, token_id, expression, return empty(xxx)
L27: ERC1155MetadataURI, return empty(xxx), immutable, self, expression
L28: Native fractionalization, return empty(xxx), expression

### CODE REVIEW

**Comment by hattiepwvi** [comment]
all _check_on_xxx
e.g.

@internal
def _check_on_erc721_received(_from: address, _to: address, _token_id: uint256, _data: Bytes[1024]) -> bool:
    if (_to.is_contract):
        return_value: bytes4 = ERC721Receiver(_to).onERC721Received(msg.sender, _from, _token_id, _data)
        assert return_value == method_id("onERC721Received(address,address,uint256,bytes)", output_type=bytes4)
        return True
    else:
        return True
        
        
        -------------------------------------------------------------------------------------------------------------
        all test

**Comment by AmazingAng** [comment]
need to resolve conflict before merging.

**Comment by hattiepwvi** [comment]
I would like to try, could I have the right to solve the conflict

**Comment by AmazingAng** [comment]
你可以revolve conflict，直接改pr就行

**Pull request closed without merging**
